### ISSUE TITLE
--unsafe-perm

### ISSUE THREAD

**Issue by wwhwwhwwh** [awesome-starter/create-preset#29]
preset init 可能会出现以下错误
✖ Operation cancelled
node:internal/readline/emitKeypressEvents:71
            throw err;
            ^
TypeError: Cannot read properties of undefined (reading 'disabled')
    at SelectPrompt.submit (C:\Users\69046\AppData\Roaming\npm\node_modules\create-preset\node_modules\_prompts@2.4.2@prompts\lib\elements\select.js:68:25)
    at ReadStream.keypress (C:\Users\69046\AppData\Roaming\npm\node_modules\create-preset\node_modules\_prompts@2.4.2@prompts\lib\elements\prompt.js:32:16)
    at ReadStream.emit (node:events:527:28)
    at emitKeys (node:internal/readline/utils:358:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (node:internal/readline/emitKeypressEvents:61:36)
    at ReadStream.emit (node:events:539:35)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at ReadStream.Readable.push (node:internal/streams/readable:228:10)

安装需要添加 --unsafe-perm
win: npm i -g create-preset  --unsafe-perm  
mac：sudo npm -g  create-preset --unsafe-perm 
建议写进文档

**Comment by chengpeiquan** [comment]
收到！我晚点处理一下（好奇怪这个 issue 居然没有给我邮件通知，现在才看到很抱歉！

**Comment by chengpeiquan** [comment]
已更新到文档上了，谢谢！
https://preset.js.org/zh/guide.html#%E7%94%A8%E6%B3%95
